mod autoscaling;
mod cluster;
mod deployment;
mod error;
mod execution;
mod ids;
mod instance;
mod node;
mod resources;
mod workload;

pub use autoscaling::{AutoscalingPolicy, AutoscalingPolicyError};
pub use cluster::{WorkerHeartbeat, WorkerRegistration};
pub use deployment::{CanaryPlan, CanaryPlanError, Deployment, DeploymentStatus};
pub use error::CoreError;
pub use execution::{ExecutionRequest, ExecutionResult};
pub use ids::{DeploymentId, InstanceId, NodeId, WorkloadId};
pub use instance::{Instance, InstanceStatus};
pub use node::{Node, NodeStatus};
pub use resources::{ResourceCapacity, ResourceRequest};
pub use workload::{ArtifactRef, Workload, WorkloadSpec, WorkloadStatus};
