[package]
name = "vessel-control"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
reqwest.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
vessel-core = { path = "../vessel-core" }
vessel-scheduler = { path = "../vessel-scheduler" }
vessel-telemetry = { path = "../vessel-telemetry" }

[dev-dependencies]
http-body-util.workspace = true
serde_json.workspace = true
tower.workspace = true
vessel-worker = { path = "../vessel-worker" }
